#NOTICE: This is a demo file for you to get started.
#Make sure to edit and rename the file. If not renamed, the file will not be saved!

version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - webnet

networks:
  webnet:
